image:
- Visual Studio 2017
- Visual Studio 2019
- Visual Studio 2022

for:
-
  matrix:
    only:
      - image: Visual Studio 2017

  environment:
    BOOST_ROOT: C:\Libraries\boost_1_69_0
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_69_0\lib64-msvc-14.1

  build_script:
    - md build
    - cd build
    - cmake -G "Visual Studio 15 Win64" ..
    - cmake --build . --config Release

-
  matrix:
    only:
      - image: Visual Studio 2019

  build_script:
    - md build
    - cd build
    - cmake -DBOOST_ROOT=C:\Libraries\boost_1_73_0 -DBOOST_LIBRARYDIR=C:\Libraries\boost_1_73_0\lib64-msvc-14.2 -G "Visual Studio 16 2019" ..
    - cmake --build . --config Release

-
  matrix:
    only:
      - image: Visual Studio 2022

  build_script:
    - md build
    - cd build
    - cmake -DBOOST_ROOT=C:\Libraries\boost_1_73_0 -DBOOST_LIBRARYDIR=C:\Libraries\boost_1_73_0\lib64-msvc-14.2 -G "Visual Studio 17 2022" ..
    - cmake --build . --config Release