name: CI CMake
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  ci-cmake:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Ubuntu 22.04 GCC 9
            os: ubuntu-22.04
            c_compiler: gcc-9
            cxx_compiler: g++-9
            packages: build-essential python3-dev gcc-9 g++-9 git cmake libboost1.74-all-dev libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev

          - name: Ubuntu 22.04 GCC 10
            os: ubuntu-22.04
            c_compiler: gcc-10
            cxx_compiler: g++-10
            packages: build-essential python3-dev gcc-10 g++-10 git cmake libboost1.74-all-dev libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev

          - name: Ubuntu 22.04 GCC 11
            os: ubuntu-22.04
            c_compiler: gcc-11
            cxx_compiler: g++-11
            packages: build-essential python3-dev gcc-11 g++-11 git cmake libboost1.74-all-dev libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev

          - name: Ubuntu 22.04 GCC 12
            os: ubuntu-22.04
            c_compiler: gcc-12
            cxx_compiler: g++-12
            packages: build-essential python3-dev gcc-12 g++-12 git cmake libboost1.74-all-dev libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev

          - name: Ubuntu 22.04 Clang 11
            os: ubuntu-22.04
            c_compiler: clang-11
            cxx_compiler: clang++-11
            packages: build-essential python3-dev clang-11 git cmake libboost1.74-all-dev libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev

          - name: Ubuntu 22.04 Clang 12
            os: ubuntu-22.04
            c_compiler: clang-12
            cxx_compiler: clang++-12
            packages: build-essential python3-dev clang-12 git cmake libboost1.74-all-dev libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev

          - name: Ubuntu 22.04 Clang 13
            os: ubuntu-22.04
            c_compiler: clang-13
            cxx_compiler: clang++-13
            packages: build-essential python3-dev clang-13 git cmake libboost1.74-all-dev libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev

          - name: Ubuntu 22.04 Clang 14
            os: ubuntu-22.04
            c_compiler: clang-14
            cxx_compiler: clang++-14
            packages: build-essential python3-dev clang-14 git cmake libboost1.74-all-dev libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev

          - name: Ubuntu 22.04 Clang 15
            os: ubuntu-22.04
            c_compiler: clang-15
            cxx_compiler: clang++-15
            packages: build-essential python3-dev clang-15 git cmake libboost1.74-all-dev libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev

          - name: Ubuntu 24.04 GCC 13
            os: ubuntu-24.04
            c_compiler: gcc-13
            cxx_compiler: g++-13
            packages: build-essential python3-dev gcc-13 g++-13 git cmake libboost1.83-all-dev libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev

          - name: Ubuntu 24.04 GCC 14
            os: ubuntu-24.04
            c_compiler: gcc-14
            cxx_compiler: g++-14
            packages: build-essential python3-dev gcc-14 g++-14 git cmake libboost1.83-all-dev libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev

          - name: Ubuntu 24.04 Clang 16
            os: ubuntu-24.04
            c_compiler: clang-16
            cxx_compiler: clang++-16
            packages: build-essential python3-dev clang-16 git cmake libboost1.83-all-dev libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev

          - name: Ubuntu 24.04 Clang 17
            os: ubuntu-24.04
            c_compiler: clang-17
            cxx_compiler: clang++-17
            packages: build-essential python3-dev clang-17 git cmake libboost1.83-all-dev libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev

          - name: Ubuntu 24.04 Clang 18
            os: ubuntu-24.04
            c_compiler: clang-18
            cxx_compiler: clang++-18
            packages: build-essential python3-dev clang-18 git cmake libboost1.83-all-dev libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.packages }}

    - name: Generate project files
      run: |
        mkdir -p build
        cd build
        cmake ..
      env:
        CC: ${{ matrix.c_compiler }}
        CXX: ${{ matrix.cxx_compiler }}

    - name: Compile source code
      run: |
        cd build
        cmake --build .
